# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


default: &default
  facts_per_page: 15
  datasets:
    chicago:
      index_url: https://data.cityofchicago.org/browse?sortBy=alpha&utf8=%E2%9C%93&page=1
      table_url: https://data.cityofchicago.org/api/views/%{dataset_id}/rows.csv?accessType=DOWNLOAD

  soda:
    app_token: <%= ENV['SODA_TOKEN'] %>
    chicago:
      domain: data.cityofchicago.org

development:
  <<: *default
  secret_key_base: d462775f110a9b844f5b2070e85826dbec275123a51cba77881ea65917829a3ce0f11287630a395724cea1d3670de873d414e7a7216764435cd9a5c5ed5d28e2

test:
  <<: *default
  secret_key_base: b20f8622ba2eb7f0930d44ac8901e56fcf3796a2f21c182252158e14eb83cb71fb34b79d1724b5322a5ae6346b6633769a120dd197d637a2093b86517df82565
